config/routes.rb
Rails.application.routes.draw do
  scope ENV['COMICDB_MOUNTED_FOLDER'] || '/' do
    devise_for :users

    resources :comics
    resources :recommendations, only: [:index]
    resources :comic_statistics, only: [:index]

    get 'attributions' => 'index#attributions'

    root 'comics#index'

    namespace :api, defaults: { format: :json } do
      namespace :v1 do
        resources :comics
      end
    end

  end
end

app/models/comic.rb
# Represents a comic series (with a single title, so spinoffs and specials
# would be a separate comic) for a single user
class Comic < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true, length: { minimum: 1 }
  validates :total_issues, presence: true, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0
  }
  validates :next_issue_to_read, presence: true, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0
  }
  validates :has_issue_zero, inclusion: [true, false]
  validates :no_more_issues, inclusion: [true, false]
  validate :must_be_valid_issues_owned, :highest_issue_owned_less_than_total_issues,
    :must_be_valid_issues_removed, :missing_from_storage_must_be_only_issues_owned

  def expanded_issues_owned
    @expanded_issues_owned ||= Comicdb::MultiRangeParser.new(issues_owned).expanded_numbers
  end

  def expanded_issues_removed_from_storage
    @expanded_issues_removed_from_storage ||= Comicdb::MultiRangeParser.new(issues_removed_from_storage).expanded_numbers
  end

  def missing_issues
    @collapsed_missing_issues ||= Comicdb::MultiRangeConstructor.new(all_missing_issues).multi_range
  end

  def all_missing_issues
    @all_missing_issues ||= (first_issue_in_series..total_issues).each_with_object([]) do |issue, missing|
      missing << issue unless expanded_issues_owned.include? issue
    end
  end

  def started_reading?
    return false if no_issues_owned?

    first_issue_owned < next_issue_to_read
  end

  def finished_reading?
    return false if no_issues_owned?

    next_issue_to_read > total_issues
  end

  def more_to_read?
    return false if no_issues_owned?

    next_issue_to_read <= last_issue_owned
  end

  def first_issue_in_series
    has_issue_zero? ? 0 : 1
  end

  def first_issue_owned
    return -1 if no_issues_owned?

    expanded_issues_owned.first
  end

  def last_issue_owned
    return -1 if no_issues_owned?

    expanded_issues_owned.last
  end

  def all_issues_owned?
    return false if no_issues_owned?

    all_missing_issues.empty?
  end

  def next_issue_available?
    return false if no_issues_owned?

    next_issue = next_issue_to_read

    next_issue = first_issue_in_series if next_issue < first_issue_in_series

    expanded_issues_owned.include? next_issue
  end

  def any_issues_removed_from_storage?
    !expanded_issues_removed_from_storage.empty?
  end

  def number_of_issues_read
    issues_owned_lower_than_next_to_read = expanded_issues_owned.select { |i| i < next_issue_to_read }
    issues_owned_lower_than_next_to_read.size
  end

  private

  def no_issues_owned?
    issues_owned.blank?
  end

  def must_be_valid_issues_owned
    expanded_issues_owned
  rescue Comicdb::MultiRangeInvalidError => e
    errors.add(:issues_owned, "Invalid listing of issues owned, #{e.message}")
  end

  def total_issues_nil?
    if total_issues.nil?
      errors.add(:total_issues, 'total issues can not be nil')
      return true
    end

    false
  end

  def highest_issue_owned_less_than_total_issues
    return if total_issues_nil?

    return if issues_owned.blank?

    max_issue_owned = expanded_issues_owned.max

    return if total_issues >= max_issue_owned

    errors.add(:issues_owned, "max value [#{max_issue_owned}] greater than total issues")
  rescue Comicdb::MultiRangeInvalidError => e
    errors.add(:issues_owned, "Invalid listing of issues owned, #{e.message}")
  end

  def must_be_valid_issues_removed
    expanded_issues_removed_from_storage
  rescue Comicdb::MultiRangeInvalidError => e
    errors.add(:issues_removed_from_storage, "Invalid listing of issues removed from storage, #{e.message}")
  end

  def missing_from_storage_must_be_only_issues_owned
    missing_from_storage_but_not_owned = (expanded_issues_removed_from_storage - expanded_issues_owned)

    return if missing_from_storage_but_not_owned.empty?

    missing_issues_range = Comicdb::MultiRangeConstructor.new(missing_from_storage_but_not_owned).multi_range

    errors.add(
      :issues_removed_from_storage,
      "All issues missing from storage must be owned, issues #{missing_issues_range} are not owned " \
        "but have been listed as missing from storage"
    )
  rescue Comicdb::MultiRangeInvalidError => e
    errors.add(:issues_removed_from_storage, "Invalid listing of issues removed from storage, #{e.message}")
  end
end

app/controllers/api/v1/comics_controller.rb
module Api
  module V1
    # Comics controller for the API
    class ComicsController < Api::V1::ApplicationController
      before_action :authenticate_user_from_token!
      before_action :authenticate_user!

      respond_to :json

      rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

      def index
        respond_with current_user.comics.order(:title).all
      end

      def show
        respond_with current_user.comics.find(params[:id])
      end

      private

      def record_not_found(_error)
        render json: { error: 'Comic not found' }, status: :not_found
      end

      def authenticate_user_from_token!
        email = request.headers['X-User-Email'].presence
        user = email && User.find_by_email(email)

        token = request.headers['X-User-Token'].presence

        # Don't even attempt to auth anyone if they have not provided a token
        return if token.blank?

        # Notice how we use Devise.secure_compare to compare the token
        # in the database with the token given in the params, mitigating
        # timing attacks.
        sign_in user, store: false if user && token && Devise.secure_compare(user.authentication_token, token)
      end
    end
  end
end

app/controllers/comics_controller.rb
# This controller deals with all actions related to the Comic model
class ComicsController < ApplicationController
  before_action :authenticate_user!

  def index
    @comics = current_user.comics.order(:title).all
  end

  def show
    @comic = current_user.comics.find(params[:id])
  end

  def new
    @comic = current_user.comics.new
  end

  def edit
    @comic = current_user.comics.find(params[:id])
  end

  def create
    @comic = current_user.comics.new(comic_params)

    if @comic.save
      redirect_to @comic
    else
      render 'new'
    end
  end

  def update
    @comic = current_user.comics.find(params[:id])

    if @comic.update(comic_params)
      redirect_to @comic
    else
      render 'edit'
    end
  end

  def destroy
    current_user.comics.find(params[:id]).destroy

    redirect_to comics_path
  end

  private

  def comic_params
    params.require(:comic).permit(
      :title, :total_issues, :url, :issues_owned, :issues_removed_from_storage,
      :next_issue_to_read, :has_issue_zero, :no_more_issues,
      :notes
    )
  end
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/views/comics/_comics_table.html.erb
<table class="table table-striped comics-list">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:total_issues) %></th>
      <th><%= model_class.human_attribute_name(:next_issue_to_read) %></th>
      <th><%= model_class.human_attribute_name(:issues_owned) %></th>
      <th><%= t('status') %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% comics.each do |comic| %>
      <tr>
        <td><%= link_to comic.title, comic_path(comic)  %></td>
        <td><%= comic.total_issues %></td>
        <td><%= comic.next_issue_to_read %></td>
        <td><%= comic.issues_owned %></td>
        <td>
          <%=
            image_tag(
              (comic.no_more_issues ? 'stop-enabled.png' : 'stop-disabled.png' ),
              alt: (comic.no_more_issues ? t('no_more_issues') : t('has_more_issues') ),
              title: (comic.no_more_issues ? t('no_more_issues') : t('has_more_issues') ),
              size: '16'
            )
          %>
          <%=
            image_tag(
              (comic.has_issue_zero ? 'zero-enabled.png' : 'zero-disabled.png' ),
              alt: (comic.has_issue_zero ? t('has_zero_issue') : t('no_zero_issue') ),
              title: (comic.has_issue_zero ? t('has_zero_issue') : t('no_zero_issue') ),
              size: '16'
            )
          %>
          <%=
            image_tag(
              (comic.all_issues_owned? ? 'missing-issues-disabled.png' : 'missing-issues-enabled.png' ),
              alt: (comic.all_issues_owned? ? t('all_issues_owned') : t('issues_missing') ),
              title: (comic.all_issues_owned? ? t('all_issues_owned') : t('issues_missing') ),
              size: '16'
            )
          %>
          <%=
            image_tag(
              (comic.started_reading? && !comic.finished_reading? ? 'play-enabled.png' : 'play-disabled.png' ),
              alt: (comic.started_reading? && !comic.finished_reading? ? t('started_reading') : t('not_started_reading') ),
              title: (comic.started_reading? && !comic.finished_reading? ? t('started_reading') : t('not_started_reading') ),
              size: '16'
            )
          %>
          <%=
            image_tag(
              (comic.finished_reading? ? 'check-mark-enabled.png' : 'check-mark-disabled.png' ),
              alt: (comic.finished_reading? ? t('finished_reading') : t('not_finished_reading') ),
              title: (comic.finished_reading? ? t('finished_reading') : t('not_finished_reading') ),
              size: '19'
            )
          %>
          <%=
            if !comic.notes.blank?
              content_tag(
                :div,
                image_tag('note-enabled.png', alt: t('has_notes'), size: '16'),
                data: {
                  html: "true",
                  toggle: "popover",
                  trigger: "hover",
                  placement: "left",
                  content: simple_format(comic.notes, class: 'notes-formatted')
                },
                class: 'notes-icon'
              )
            else
              image_tag('note-disabled.png', alt: t('no_notes'), size: '16')
            end
          %>
        </td>
        <td>
          <%=
            link_to(
              image_tag(
                'edit.svg',
                alt: t('.edit', :default => t("helpers.links.edit")),
                title: t('.edit', :default => t("helpers.links.edit")),
                size: '16'
              ),
              edit_comic_path(comic)
            )
          %>
          <%=
            link_to(
              image_tag(
                'delete.svg',
                alt: t('.destroy', :default => t("helpers.links.destroy")),
                title: t('.destroy', :default => t("helpers.links.destroy")),
                size: '14'
              ),
              comic_path(comic),
              :method => :delete,
              :data => {
                :confirm => t(
                  '.confirm',
                  :default => t("helpers.links.confirm", :default => 'Are you sure?')
                )
              }
            )
          %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/comics/_form.html.erb
<%= form_for @comic, :html => { :class => "form-horizontal comic" } do |f| %>

  <% if @comic.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@comic.errors.count, "error") %> prohibited this comic from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @comic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'form-control', autofocus: true %>
    </div>
    <%= f.error_span :title %>
  </div>
  <div class="control-group">
    <%= f.label :total_issues, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :total_issues, min: 0, step: 1, :class => 'form-control' %>
    </div>
    <%= f.error_span :total_issues %>
  </div>
  <div class="control-group">
    <%= f.label :has_issue_zero, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :has_issue_zero, :class => 'form-control' %>
    </div>
    <%= f.error_span :has_issue_zero %>
  </div>
  <div class="control-group">
    <%= f.label :no_more_issues, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :no_more_issues, :class => 'form-control' %>
    </div>
    <%= f.error_span :no_more_issues %>
  </div>
  <div class="control-group">
    <%= f.label :issues_owned, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :issues_owned, :class => 'form-control' %>
    </div>
    <%= f.error_span :issues_owned %>
  </div>
  <div class="control-group">
    <%= f.label :issues_removed_from_storage, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :issues_removed_from_storage, :class => 'form-control' %>
    </div>
    <%= f.error_span :issues_removed_from_storage %>
  </div>
  <div class="control-group">
    <%= f.label :next_issue_to_read, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :next_issue_to_read, min: 0, step: 1, :class => 'form-control' %>
    </div>
    <%= f.error_span :next_issue_to_read %>
  </div>
  <div class="control-group">
    <%= f.label :notes, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :notes, :class => 'form-control' %>
    </div>
    <%= f.error_span :notes %>
  </div>
  <div class="control-group">
    <%= f.label :url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :url, :class => 'form-control' %>
    </div>
    <%= f.error_span :url %>
  </div>


  <div style="margin-top: 15px">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
              comics_path, :class => 'btn btn-default' %>
  </div>

<% end %>

<script>
$(document).ready(function() {
  $('#comic_has_issue_zero').change(function() {
    var next_issue_field = $('#comic_next_issue_to_read');
    if(this.checked) {
      if (next_issue_field.val() == 1) {
        next_issue_field.val(0);
      }
    } else {
      if (next_issue_field.val() == 0) {
        next_issue_field.val(1);
      }
    }
  });
});
</script>

app/views/comics/edit.html.erb
<%- model_class = Comic -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/comics/index.html.erb
<%- model_class = Comic -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= render partial: "comics_table", locals: { comics: @comics, model_class: model_class }  %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_comic_path,
            :class => 'btn btn-primary' %>

app/views/comics/new.html.erb
<%- model_class = Comic -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/comics/show.html.erb
<%- model_class = Comic -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @comic.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:total_issues) %>:</strong></dt>
  <dd><%= @comic.total_issues %></dd>
  <dt><strong><%= model_class.human_attribute_name(:has_issue_zero) %>:</strong></dt>
  <dd><%= @comic.has_issue_zero %></dd>
  <dt><strong><%= model_class.human_attribute_name(:no_more_issues) %>:</strong></dt>
  <dd><%= @comic.no_more_issues %></dd>
  <dt><strong><%= model_class.human_attribute_name(:issues_owned) %>:</strong></dt>
  <dd><%= @comic.issues_owned %></dd>
  <dt><strong><%= model_class.human_attribute_name(:issues_removed_from_storage) %>:</strong></dt>
  <dd><%= @comic.issues_removed_from_storage %></dd>
  <dt><strong><%= model_class.human_attribute_name(:next_issue_to_read) %>:</strong></dt>
  <dd><%= @comic.next_issue_to_read %></dd>
  <dt><strong><%= model_class.human_attribute_name(:notes) %>:</strong></dt>
  <dd><%= simple_format @comic.notes, class: 'notes-formatted' %></dd>
  <dt><strong><%= model_class.human_attribute_name(:url) %>:</strong></dt>
  <dd><%= @comic.url %></dd>
  <dt><strong>Missing Issues</strong></dt>
  <dd class='text-danger'><%= @comic.missing_issues %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              comics_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_comic_path(@comic), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              comic_path(@comic),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>