config/routes.rb
Rails.application.routes.draw do
  scope ENV['COMICDB_MOUNTED_FOLDER'] || '/' do
    devise_for :users

    resources :comics
    resources :recommendations, only: [:index]
    resources :comic_statistics, only: [:index]

    get 'attributions' => 'index#attributions'

    root 'comics#index'

    namespace :api, defaults: { format: :json } do
      namespace :v1 do
        resources :comics
      end
    end

  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Comicdb" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <%= link_to "Comicdb", comics_path, class: "navbar-brand"  %></li>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
            <ul class="nav navbar-nav">
                <% if user_signed_in? %>
                    <li><%= link_to t('.home', :default => t("helpers.links.list")), comics_path %></li>
                    <li><%= link_to t('.new', :default => t("helpers.links.new")), new_comic_path %></li>
                    <li><%= link_to t('recommendations'), recommendations_path %></li>
                    <li><%= link_to t('comic_statistics_heading'), comic_statistics_path %></li>
                    <li><%= link_to t('edituser'), edit_user_registration_path %></li>
                    <li><%= link_to t('logout'), destroy_user_session_path, method: :delete %></li>
                <% else %>
                    <li><%= link_to t('login'), new_user_session_path %></li>
                    <li><%= link_to t('signup'), new_user_registration_path %></li>
                <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; J F Harden 2015 - <%= link_to t('attributions'), controller: '/index', action: 'attributions' %></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>